# Generated by Django 4.2.7 on 2025-10-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanfoods', '0002_pushsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', ' Pending'), ('preparing', ' Preparing'), ('out_for_delivery', ' Out for Delivery'), ('delivered', ' Delivered'), ('cancelled', ' Cancelled')], default='pending', max_length=20),
        ),
    ]
