# Generated by Django 4.2.7 on 2025-10-03 11:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanfoods', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodreview',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
