# Generated by Django 4.2.7 on 2025-12-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanfoods', '0004_alter_foodreview_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcategory',
            name='store_type',
            field=models.CharField(choices=[('food', 'Food Store'), ('liquor', 'Liquor Store')], default='food', max_length=10),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='bottle_size',
            field=models.CharField(blank=True, help_text='For liquor items (e.g., 250ml, 500ml, 750ml)', max_length=20),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='store_type',
            field=models.CharField(choices=[('food', 'Food Store'), ('liquor', 'Liquor Store')], default='food', max_length=10),
        ),
    ]
