# Generated by Django 4.2.7 on 2025-12-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanfoods', '0005_foodcategory_store_type_fooditem_bottle_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategory',
            name='store_type',
            field=models.CharField(choices=[('food', 'Food Store'), ('liquor', 'Liquor Store'), ('grocery', 'Grocery Shop')], default='food', max_length=10),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='store_type',
            field=models.CharField(choices=[('food', 'Food Store'), ('liquor', 'Liquor Store'), ('grocery', 'Grocery Shop')], default='food', max_length=10),
        ),
    ]
