# Generated by Django 4.2.7 on 2025-12-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanfoods', '0007_order_mpesa_checkout_request_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('till', 'Till Number'), ('paybill', 'Paybill Number')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='store_type',
            field=models.CharField(choices=[('food', 'Food Store'), ('liquor', 'Liquor Store'), ('grocery', 'Grocery Shop')], default='food', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'MPESA')], default='mpesa', max_length=10),
        ),
    ]
