# Generated by Django 4.2.7 on 2026-01-04 16:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanfoods', '0008_order_payment_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('payment_pending', 'Payment Pending'), ('pending', 'Pending'), ('preparing', ' Preparing'), ('out_for_delivery', ' Out for Delivery'), ('delivered', ' Delivered'), ('cancelled', ' Cancelled')], default='pending', max_length=20),
        ),
    ]
