# Generated by Django 4.2.7 on 2026-01-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanfoods', '0009_alter_order_rating_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'MPESA'), ('till', 'TILL')], default='till', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('payment_pending', 'Payment Pending'), ('pending', 'Pending'), ('preparing', ' Preparing'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
