# Generated by Django 4.2.7 on 2026-01-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanfoods', '0010_alter_order_payment_method_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='estimated_delivery',
            field=models.DateTimeField(blank=True, default=30, null=True),
        ),
    ]
