# Generated by Django 4.2.7 on 2026-01-07 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanfoods', '0011_alter_order_estimated_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_test_order',
            field=models.BooleanField(default=False),
        ),
    ]
