# Generated by Django 4.2.7 on 2026-01-07 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urbanfoods', '0012_order_is_test_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_test_order',
        ),
    ]
